# Generated by Django 5.2.1 on 2025-10-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('avatar_name', models.CharField(max_length=100, verbose_name='VRChatアバター名')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='トップ画像')),
                ('introduction', models.TextField(verbose_name='自己紹介文')),
                ('reason_for_vrc', models.TextField(verbose_name='VRChatを始めた理由')),
                ('hobbies', models.TextField(verbose_name='趣味')),
                ('favorite_things', models.TextField(verbose_name='好きなこと')),
                ('career_goal', models.CharField(max_length=200, verbose_name='目指している仕事')),
            ],
        ),
    ]
