# Generated by Django 5.2.1 on 2025-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無しさん', max_length=100, verbose_name='名前')),
                ('vrchat_id', models.CharField(blank=True, max_length=100, verbose_name='VRChat ID')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('discord_id', models.CharField(blank=True, max_length=100, verbose_name='Discord ID')),
                ('bio', models.TextField(blank=True, verbose_name='自己紹介文')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='アイコン画像')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='背景画像')),
            ],
        ),
    ]
