# Generated by Django 5.2.1 on 2025-10-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='背景画像'),
        ),
        migrations.AddField(
            model_name='profile',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='アイコン画像'),
        ),
    ]
